# Generated by Django 5.0.1 on 2024-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amountingredients",
            old_name="count",
            new_name="weight",
        ),
        migrations.AlterField(
            model_name="product",
            name="count_of_use",
            field=models.IntegerField(
                default=0, verbose_name="Количество раз использовано в рецептах"
            ),
        ),
    ]
